# Run unit & integration tests
on: 
  push:
    paths-ignore:
      - 'docs/**'  # only trigger build if a file outside of /docs was changed
      - '_locales/*.xml'
      - '.vscode/**'
      - 'README_ASSETS/**'
      - 'README.md'

jobs:
  test:
    name: Tests #and E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest doesn't work currently: ERROR UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.
      fail-fast: false # don't fail fast, because some tests can be flaky so better we get all results
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Set version info
      shell: bash
      run: |
        echo "VERSION_INFO_GIT_REF=${{ github.sha }}-${{ github.ref_name }}" >> $GITHUB_ENV
    - name: build
      run: |
        pnpm run build
    - name: test
      run: |
        pnpm run test

